#!/usr/bin/env bash
#
# Generate a page with my socials
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: March 17, 2024
# License: MIT

. ./colors || exit 1
. ./util || exit 1

echo -e "${GRAY_COLOR}# Also find me at${RST_COLOR}
${GRAY_COLOR}+ --------- + ------------------------------------- +${RST_COLOR}
${GRAY_COLOR}| ${GREEN_COLOR}Github   ${GRAY_COLOR} | ${BLUE_COLOR}https://github.com/bottiger           ${GRAY_COLOR}|${RST_COLOR}
${GRAY_COLOR}| ${GREEN_COLOR}LinkedIn ${GRAY_COLOR} | ${BLUE_COLOR}https://www.linkedin.com/in/bottiger/ ${GRAY_COLOR}|${RST_COLOR}
${GRAY_COLOR}+ --------- + ------------------------------------- +${RST_COLOR}"
